# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l0fT0fvP0a5HX3i-JVP6ocHBUhzCE6Gt
"""

import pandas as pd
import numpy as np
import os
import joblib

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


def run_preprocessing(input_path, output_dir="namadataset_preprocessing"):
    """
    Fungsi untuk melakukan preprocessing otomatis
    """

    # Load data
    df = pd.read_csv("healthcare-dataset-stroke-data.csv")

    # Handle missing value
    df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

    # Drop kolom tidak penting
    if 'id' in df.columns:
        df.drop(['id'], axis=1, inplace=True)

    # Split fitur dan target
    X = df.drop('stroke', axis=1)
    y = df['stroke']

    # Encoding
    X = pd.get_dummies(X, drop_first=True)

    # Scaling
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    # Buat folder output
    os.makedirs(output_dir, exist_ok=True)

    # Simpan hasil
    joblib.dump(X_train, f"{output_dir}/X_train.joblib")
    joblib.dump(X_test, f"{output_dir}/X_test.joblib")
    joblib.dump(y_train, f"{output_dir}/y_train.joblib")
    joblib.dump(y_test, f"{output_dir}/y_test.joblib")
    joblib.dump(scaler, f"{output_dir}/scaler.joblib")

    print("✅ Preprocessing otomatis selesai!")
    return X_train, X_test, y_train, y_test


# Jika dijalankan langsung
if __name__ == "__main__":
    run_preprocessing("healthcare-dataset-stroke-data.csv")